package com.example.user.model;

import java.util.Date;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.id
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.user_id
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.role_id
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.delete_flag
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.ctime
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.utime
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private Date utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.dtime
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private Date dtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.operator
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private String operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.id
     *
     * @return the value of user_role.id
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.id
     *
     * @param id the value for user_role.id
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.user_id
     *
     * @return the value of user_role.user_id
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.user_id
     *
     * @param userId the value for user_role.user_id
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.role_id
     *
     * @return the value of user_role.role_id
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.role_id
     *
     * @param roleId the value for user_role.role_id
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.delete_flag
     *
     * @return the value of user_role.delete_flag
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.delete_flag
     *
     * @param deleteFlag the value for user_role.delete_flag
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.ctime
     *
     * @return the value of user_role.ctime
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.ctime
     *
     * @param ctime the value for user_role.ctime
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.utime
     *
     * @return the value of user_role.utime
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.utime
     *
     * @param utime the value for user_role.utime
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.dtime
     *
     * @return the value of user_role.dtime
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public Date getDtime() {
        return dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.dtime
     *
     * @param dtime the value for user_role.dtime
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setDtime(Date dtime) {
        this.dtime = dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.operator
     *
     * @return the value of user_role.operator
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.operator
     *
     * @param operator the value for user_role.operator
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }
}