package com.example.user.model;

import java.util.Date;

public class UserPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.id
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.role
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.function
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private String function;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.service_id
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private String serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.visible_function
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private Boolean visibleFunction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.add_function
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private Boolean addFunction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.update_function
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private Boolean updateFunction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.delete_function
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private Boolean deleteFunction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.ctime
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.utime
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private Date utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission.operator
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private String operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.id
     *
     * @return the value of user_permission.id
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.id
     *
     * @param id the value for user_permission.id
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.role
     *
     * @return the value of user_permission.role
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.role
     *
     * @param role the value for user_permission.role
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.function
     *
     * @return the value of user_permission.function
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public String getFunction() {
        return function;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.function
     *
     * @param function the value for user_permission.function
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setFunction(String function) {
        this.function = function;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.service_id
     *
     * @return the value of user_permission.service_id
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.service_id
     *
     * @param serviceId the value for user_permission.service_id
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.visible_function
     *
     * @return the value of user_permission.visible_function
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public Boolean getVisibleFunction() {
        return visibleFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.visible_function
     *
     * @param visibleFunction the value for user_permission.visible_function
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setVisibleFunction(Boolean visibleFunction) {
        this.visibleFunction = visibleFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.add_function
     *
     * @return the value of user_permission.add_function
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public Boolean getAddFunction() {
        return addFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.add_function
     *
     * @param addFunction the value for user_permission.add_function
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setAddFunction(Boolean addFunction) {
        this.addFunction = addFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.update_function
     *
     * @return the value of user_permission.update_function
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public Boolean getUpdateFunction() {
        return updateFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.update_function
     *
     * @param updateFunction the value for user_permission.update_function
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setUpdateFunction(Boolean updateFunction) {
        this.updateFunction = updateFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.delete_function
     *
     * @return the value of user_permission.delete_function
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public Boolean getDeleteFunction() {
        return deleteFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.delete_function
     *
     * @param deleteFunction the value for user_permission.delete_function
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setDeleteFunction(Boolean deleteFunction) {
        this.deleteFunction = deleteFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.ctime
     *
     * @return the value of user_permission.ctime
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.ctime
     *
     * @param ctime the value for user_permission.ctime
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.utime
     *
     * @return the value of user_permission.utime
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.utime
     *
     * @param utime the value for user_permission.utime
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission.operator
     *
     * @return the value of user_permission.operator
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission.operator
     *
     * @param operator the value for user_permission.operator
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }
}