package com.example.invoke.dao;

import com.example.invoke.model.Bbb;
import com.example.invoke.model.BbbExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository(value = "bbbMapper")
public interface BbbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbb
     *
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    int countByExample(BbbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbb
     *
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    int deleteByExample(BbbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbb
     *
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbb
     *
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    int insert(Bbb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbb
     *
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    int insertSelective(Bbb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbb
     *
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    List<Bbb> selectByExample(BbbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbb
     *
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    Bbb selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbb
     *
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") Bbb record, @Param("example") BbbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbb
     *
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    int updateByExample(@Param("record") Bbb record, @Param("example") BbbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbb
     *
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    int updateByPrimaryKeySelective(Bbb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbb
     *
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    int updateByPrimaryKey(Bbb record);

    @Select(value = "select category from bbb group by category")
    List<String> getCategory();

    @Select(value = "select id from bbb group by id")
    List<Integer> getAllId();

    List<Bbb> getPageBook(Map paras);
}