package com.example.invoke.dao;

import com.example.invoke.dto.CommonDto;
import com.example.invoke.model.Miui;
import com.example.invoke.model.MiuiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

@Repository(value = "miuiMapper")
public interface MiuiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    int countByExample(MiuiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    int deleteByExample(MiuiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    int insert(Miui record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    int insertSelective(Miui record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    List<Miui> selectByExample(MiuiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    Miui selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") Miui record, @Param("example") MiuiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    int updateByExample(@Param("record") Miui record, @Param("example") MiuiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    int updateByPrimaryKeySelective(Miui record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    int updateByPrimaryKey(Miui record);
    @Select(value = "SELECT COUNT(author) value1,author category FROM miui GROUP BY author ORDER BY value1 desc limit 0,7")
    List<CommonDto> topAuthors();
    @Select(value = "SELECT COUNT(phone_type) value1,phone_type category FROM miui WHERE phone_type like \"%米%\" GROUP BY phone_type ORDER BY value1 desc limit 0,7")
    List<CommonDto> topPhoneTypes();
}