package com.example.invoke.dao;

import com.example.invoke.model.Music;
import com.example.invoke.model.MusicExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository(value = "musicMapper")
public interface MusicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    int countByExample(MusicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    int deleteByExample(MusicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    int insert(Music record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    int insertSelective(Music record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    List<Music> selectByExample(MusicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    Music selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") Music record, @Param("example") MusicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    int updateByExample(@Param("record") Music record, @Param("example") MusicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    int updateByPrimaryKeySelective(Music record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    int updateByPrimaryKey(Music record);
}