package com.example.invoke.model;

import java.io.Serializable;

public class Bbb implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbb.id
     *
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbb.title
     *
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbb.category
     *
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbb.content
     *
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbb.hot
     *
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    private Integer hot;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbb.id
     *
     * @return the value of bbb.id
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbb.id
     *
     * @param id the value for bbb.id
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbb.title
     *
     * @return the value of bbb.title
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbb.title
     *
     * @param title the value for bbb.title
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbb.category
     *
     * @return the value of bbb.category
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbb.category
     *
     * @param category the value for bbb.category
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbb.content
     *
     * @return the value of bbb.content
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbb.content
     *
     * @param content the value for bbb.content
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbb.hot
     *
     * @return the value of bbb.hot
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    public Integer getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbb.hot
     *
     * @param hot the value for bbb.hot
     * @mbggenerated Wed Jul 11 11:57:30 CST 2018
     */
    public void setHot(Integer hot) {
        this.hot = hot;
    }
}