package com.example.invoke.model;

public class Img {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.id
     *
     * @mbggenerated Fri Nov 23 15:26:39 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.name
     *
     * @mbggenerated Fri Nov 23 15:26:39 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.data
     *
     * @mbggenerated Fri Nov 23 15:26:39 CST 2018
     */
    private Object data;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Object getData() {
        return data;
    }

    public void setData(Object data) {
        this.data = data;
    }
}