package com.example.invoke.model;

public class Miui {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miui.id
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miui.author
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miui.integral
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    private String integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miui.groupx
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    private String groupx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miui.phone_type
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    private String phoneType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miui.miui_version
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    private String miuiVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miui.classify
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    private String classify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miui.title
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miui.view_nums
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    private String viewNums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miui.replies
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    private String replies;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miui.content
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miui.image_file_path
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    private String imageFilePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miui.favorit
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    private Integer favorit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miui.id
     *
     * @return the value of miui.id
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miui.id
     *
     * @param id the value for miui.id
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miui.author
     *
     * @return the value of miui.author
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miui.author
     *
     * @param author the value for miui.author
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miui.integral
     *
     * @return the value of miui.integral
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public String getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miui.integral
     *
     * @param integral the value for miui.integral
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public void setIntegral(String integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miui.groupx
     *
     * @return the value of miui.groupx
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public String getGroupx() {
        return groupx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miui.groupx
     *
     * @param groupx the value for miui.groupx
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public void setGroupx(String groupx) {
        this.groupx = groupx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miui.phone_type
     *
     * @return the value of miui.phone_type
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public String getPhoneType() {
        return phoneType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miui.phone_type
     *
     * @param phoneType the value for miui.phone_type
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public void setPhoneType(String phoneType) {
        this.phoneType = phoneType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miui.miui_version
     *
     * @return the value of miui.miui_version
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public String getMiuiVersion() {
        return miuiVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miui.miui_version
     *
     * @param miuiVersion the value for miui.miui_version
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public void setMiuiVersion(String miuiVersion) {
        this.miuiVersion = miuiVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miui.classify
     *
     * @return the value of miui.classify
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public String getClassify() {
        return classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miui.classify
     *
     * @param classify the value for miui.classify
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public void setClassify(String classify) {
        this.classify = classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miui.title
     *
     * @return the value of miui.title
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miui.title
     *
     * @param title the value for miui.title
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miui.view_nums
     *
     * @return the value of miui.view_nums
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public String getViewNums() {
        return viewNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miui.view_nums
     *
     * @param viewNums the value for miui.view_nums
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public void setViewNums(String viewNums) {
        this.viewNums = viewNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miui.replies
     *
     * @return the value of miui.replies
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public String getReplies() {
        return replies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miui.replies
     *
     * @param replies the value for miui.replies
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public void setReplies(String replies) {
        this.replies = replies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miui.content
     *
     * @return the value of miui.content
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miui.content
     *
     * @param content the value for miui.content
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miui.image_file_path
     *
     * @return the value of miui.image_file_path
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public String getImageFilePath() {
        return imageFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miui.image_file_path
     *
     * @param imageFilePath the value for miui.image_file_path
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public void setImageFilePath(String imageFilePath) {
        this.imageFilePath = imageFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miui.favorit
     *
     * @return the value of miui.favorit
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public Integer getFavorit() {
        return favorit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miui.favorit
     *
     * @param favorit the value for miui.favorit
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public void setFavorit(Integer favorit) {
        this.favorit = favorit;
    }
}