package com.example.invoke.model;

import java.util.ArrayList;
import java.util.List;

public class MiuiExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public MiuiExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNull() {
            addCriterion("author is null");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNotNull() {
            addCriterion("author is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorEqualTo(String value) {
            addCriterion("author =", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotEqualTo(String value) {
            addCriterion("author <>", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThan(String value) {
            addCriterion("author >", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("author >=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThan(String value) {
            addCriterion("author <", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThanOrEqualTo(String value) {
            addCriterion("author <=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLike(String value) {
            addCriterion("author like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotLike(String value) {
            addCriterion("author not like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorIn(List<String> values) {
            addCriterion("author in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotIn(List<String> values) {
            addCriterion("author not in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorBetween(String value1, String value2) {
            addCriterion("author between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotBetween(String value1, String value2) {
            addCriterion("author not between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andIntegralIsNull() {
            addCriterion("integral is null");
            return (Criteria) this;
        }

        public Criteria andIntegralIsNotNull() {
            addCriterion("integral is not null");
            return (Criteria) this;
        }

        public Criteria andIntegralEqualTo(String value) {
            addCriterion("integral =", value, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralNotEqualTo(String value) {
            addCriterion("integral <>", value, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralGreaterThan(String value) {
            addCriterion("integral >", value, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralGreaterThanOrEqualTo(String value) {
            addCriterion("integral >=", value, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralLessThan(String value) {
            addCriterion("integral <", value, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralLessThanOrEqualTo(String value) {
            addCriterion("integral <=", value, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralLike(String value) {
            addCriterion("integral like", value, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralNotLike(String value) {
            addCriterion("integral not like", value, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralIn(List<String> values) {
            addCriterion("integral in", values, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralNotIn(List<String> values) {
            addCriterion("integral not in", values, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralBetween(String value1, String value2) {
            addCriterion("integral between", value1, value2, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralNotBetween(String value1, String value2) {
            addCriterion("integral not between", value1, value2, "integral");
            return (Criteria) this;
        }

        public Criteria andGroupxIsNull() {
            addCriterion("groupx is null");
            return (Criteria) this;
        }

        public Criteria andGroupxIsNotNull() {
            addCriterion("groupx is not null");
            return (Criteria) this;
        }

        public Criteria andGroupxEqualTo(String value) {
            addCriterion("groupx =", value, "groupx");
            return (Criteria) this;
        }

        public Criteria andGroupxNotEqualTo(String value) {
            addCriterion("groupx <>", value, "groupx");
            return (Criteria) this;
        }

        public Criteria andGroupxGreaterThan(String value) {
            addCriterion("groupx >", value, "groupx");
            return (Criteria) this;
        }

        public Criteria andGroupxGreaterThanOrEqualTo(String value) {
            addCriterion("groupx >=", value, "groupx");
            return (Criteria) this;
        }

        public Criteria andGroupxLessThan(String value) {
            addCriterion("groupx <", value, "groupx");
            return (Criteria) this;
        }

        public Criteria andGroupxLessThanOrEqualTo(String value) {
            addCriterion("groupx <=", value, "groupx");
            return (Criteria) this;
        }

        public Criteria andGroupxLike(String value) {
            addCriterion("groupx like", value, "groupx");
            return (Criteria) this;
        }

        public Criteria andGroupxNotLike(String value) {
            addCriterion("groupx not like", value, "groupx");
            return (Criteria) this;
        }

        public Criteria andGroupxIn(List<String> values) {
            addCriterion("groupx in", values, "groupx");
            return (Criteria) this;
        }

        public Criteria andGroupxNotIn(List<String> values) {
            addCriterion("groupx not in", values, "groupx");
            return (Criteria) this;
        }

        public Criteria andGroupxBetween(String value1, String value2) {
            addCriterion("groupx between", value1, value2, "groupx");
            return (Criteria) this;
        }

        public Criteria andGroupxNotBetween(String value1, String value2) {
            addCriterion("groupx not between", value1, value2, "groupx");
            return (Criteria) this;
        }

        public Criteria andPhoneTypeIsNull() {
            addCriterion("phone_type is null");
            return (Criteria) this;
        }

        public Criteria andPhoneTypeIsNotNull() {
            addCriterion("phone_type is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneTypeEqualTo(String value) {
            addCriterion("phone_type =", value, "phoneType");
            return (Criteria) this;
        }

        public Criteria andPhoneTypeNotEqualTo(String value) {
            addCriterion("phone_type <>", value, "phoneType");
            return (Criteria) this;
        }

        public Criteria andPhoneTypeGreaterThan(String value) {
            addCriterion("phone_type >", value, "phoneType");
            return (Criteria) this;
        }

        public Criteria andPhoneTypeGreaterThanOrEqualTo(String value) {
            addCriterion("phone_type >=", value, "phoneType");
            return (Criteria) this;
        }

        public Criteria andPhoneTypeLessThan(String value) {
            addCriterion("phone_type <", value, "phoneType");
            return (Criteria) this;
        }

        public Criteria andPhoneTypeLessThanOrEqualTo(String value) {
            addCriterion("phone_type <=", value, "phoneType");
            return (Criteria) this;
        }

        public Criteria andPhoneTypeLike(String value) {
            addCriterion("phone_type like", value, "phoneType");
            return (Criteria) this;
        }

        public Criteria andPhoneTypeNotLike(String value) {
            addCriterion("phone_type not like", value, "phoneType");
            return (Criteria) this;
        }

        public Criteria andPhoneTypeIn(List<String> values) {
            addCriterion("phone_type in", values, "phoneType");
            return (Criteria) this;
        }

        public Criteria andPhoneTypeNotIn(List<String> values) {
            addCriterion("phone_type not in", values, "phoneType");
            return (Criteria) this;
        }

        public Criteria andPhoneTypeBetween(String value1, String value2) {
            addCriterion("phone_type between", value1, value2, "phoneType");
            return (Criteria) this;
        }

        public Criteria andPhoneTypeNotBetween(String value1, String value2) {
            addCriterion("phone_type not between", value1, value2, "phoneType");
            return (Criteria) this;
        }

        public Criteria andMiuiVersionIsNull() {
            addCriterion("miui_version is null");
            return (Criteria) this;
        }

        public Criteria andMiuiVersionIsNotNull() {
            addCriterion("miui_version is not null");
            return (Criteria) this;
        }

        public Criteria andMiuiVersionEqualTo(String value) {
            addCriterion("miui_version =", value, "miuiVersion");
            return (Criteria) this;
        }

        public Criteria andMiuiVersionNotEqualTo(String value) {
            addCriterion("miui_version <>", value, "miuiVersion");
            return (Criteria) this;
        }

        public Criteria andMiuiVersionGreaterThan(String value) {
            addCriterion("miui_version >", value, "miuiVersion");
            return (Criteria) this;
        }

        public Criteria andMiuiVersionGreaterThanOrEqualTo(String value) {
            addCriterion("miui_version >=", value, "miuiVersion");
            return (Criteria) this;
        }

        public Criteria andMiuiVersionLessThan(String value) {
            addCriterion("miui_version <", value, "miuiVersion");
            return (Criteria) this;
        }

        public Criteria andMiuiVersionLessThanOrEqualTo(String value) {
            addCriterion("miui_version <=", value, "miuiVersion");
            return (Criteria) this;
        }

        public Criteria andMiuiVersionLike(String value) {
            addCriterion("miui_version like", value, "miuiVersion");
            return (Criteria) this;
        }

        public Criteria andMiuiVersionNotLike(String value) {
            addCriterion("miui_version not like", value, "miuiVersion");
            return (Criteria) this;
        }

        public Criteria andMiuiVersionIn(List<String> values) {
            addCriterion("miui_version in", values, "miuiVersion");
            return (Criteria) this;
        }

        public Criteria andMiuiVersionNotIn(List<String> values) {
            addCriterion("miui_version not in", values, "miuiVersion");
            return (Criteria) this;
        }

        public Criteria andMiuiVersionBetween(String value1, String value2) {
            addCriterion("miui_version between", value1, value2, "miuiVersion");
            return (Criteria) this;
        }

        public Criteria andMiuiVersionNotBetween(String value1, String value2) {
            addCriterion("miui_version not between", value1, value2, "miuiVersion");
            return (Criteria) this;
        }

        public Criteria andClassifyIsNull() {
            addCriterion("classify is null");
            return (Criteria) this;
        }

        public Criteria andClassifyIsNotNull() {
            addCriterion("classify is not null");
            return (Criteria) this;
        }

        public Criteria andClassifyEqualTo(String value) {
            addCriterion("classify =", value, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyNotEqualTo(String value) {
            addCriterion("classify <>", value, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyGreaterThan(String value) {
            addCriterion("classify >", value, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyGreaterThanOrEqualTo(String value) {
            addCriterion("classify >=", value, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyLessThan(String value) {
            addCriterion("classify <", value, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyLessThanOrEqualTo(String value) {
            addCriterion("classify <=", value, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyLike(String value) {
            addCriterion("classify like", value, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyNotLike(String value) {
            addCriterion("classify not like", value, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyIn(List<String> values) {
            addCriterion("classify in", values, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyNotIn(List<String> values) {
            addCriterion("classify not in", values, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyBetween(String value1, String value2) {
            addCriterion("classify between", value1, value2, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyNotBetween(String value1, String value2) {
            addCriterion("classify not between", value1, value2, "classify");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andViewNumsIsNull() {
            addCriterion("view_nums is null");
            return (Criteria) this;
        }

        public Criteria andViewNumsIsNotNull() {
            addCriterion("view_nums is not null");
            return (Criteria) this;
        }

        public Criteria andViewNumsEqualTo(String value) {
            addCriterion("view_nums =", value, "viewNums");
            return (Criteria) this;
        }

        public Criteria andViewNumsNotEqualTo(String value) {
            addCriterion("view_nums <>", value, "viewNums");
            return (Criteria) this;
        }

        public Criteria andViewNumsGreaterThan(String value) {
            addCriterion("view_nums >", value, "viewNums");
            return (Criteria) this;
        }

        public Criteria andViewNumsGreaterThanOrEqualTo(String value) {
            addCriterion("view_nums >=", value, "viewNums");
            return (Criteria) this;
        }

        public Criteria andViewNumsLessThan(String value) {
            addCriterion("view_nums <", value, "viewNums");
            return (Criteria) this;
        }

        public Criteria andViewNumsLessThanOrEqualTo(String value) {
            addCriterion("view_nums <=", value, "viewNums");
            return (Criteria) this;
        }

        public Criteria andViewNumsLike(String value) {
            addCriterion("view_nums like", value, "viewNums");
            return (Criteria) this;
        }

        public Criteria andViewNumsNotLike(String value) {
            addCriterion("view_nums not like", value, "viewNums");
            return (Criteria) this;
        }

        public Criteria andViewNumsIn(List<String> values) {
            addCriterion("view_nums in", values, "viewNums");
            return (Criteria) this;
        }

        public Criteria andViewNumsNotIn(List<String> values) {
            addCriterion("view_nums not in", values, "viewNums");
            return (Criteria) this;
        }

        public Criteria andViewNumsBetween(String value1, String value2) {
            addCriterion("view_nums between", value1, value2, "viewNums");
            return (Criteria) this;
        }

        public Criteria andViewNumsNotBetween(String value1, String value2) {
            addCriterion("view_nums not between", value1, value2, "viewNums");
            return (Criteria) this;
        }

        public Criteria andRepliesIsNull() {
            addCriterion("replies is null");
            return (Criteria) this;
        }

        public Criteria andRepliesIsNotNull() {
            addCriterion("replies is not null");
            return (Criteria) this;
        }

        public Criteria andRepliesEqualTo(String value) {
            addCriterion("replies =", value, "replies");
            return (Criteria) this;
        }

        public Criteria andRepliesNotEqualTo(String value) {
            addCriterion("replies <>", value, "replies");
            return (Criteria) this;
        }

        public Criteria andRepliesGreaterThan(String value) {
            addCriterion("replies >", value, "replies");
            return (Criteria) this;
        }

        public Criteria andRepliesGreaterThanOrEqualTo(String value) {
            addCriterion("replies >=", value, "replies");
            return (Criteria) this;
        }

        public Criteria andRepliesLessThan(String value) {
            addCriterion("replies <", value, "replies");
            return (Criteria) this;
        }

        public Criteria andRepliesLessThanOrEqualTo(String value) {
            addCriterion("replies <=", value, "replies");
            return (Criteria) this;
        }

        public Criteria andRepliesLike(String value) {
            addCriterion("replies like", value, "replies");
            return (Criteria) this;
        }

        public Criteria andRepliesNotLike(String value) {
            addCriterion("replies not like", value, "replies");
            return (Criteria) this;
        }

        public Criteria andRepliesIn(List<String> values) {
            addCriterion("replies in", values, "replies");
            return (Criteria) this;
        }

        public Criteria andRepliesNotIn(List<String> values) {
            addCriterion("replies not in", values, "replies");
            return (Criteria) this;
        }

        public Criteria andRepliesBetween(String value1, String value2) {
            addCriterion("replies between", value1, value2, "replies");
            return (Criteria) this;
        }

        public Criteria andRepliesNotBetween(String value1, String value2) {
            addCriterion("replies not between", value1, value2, "replies");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andImageFilePathIsNull() {
            addCriterion("image_file_path is null");
            return (Criteria) this;
        }

        public Criteria andImageFilePathIsNotNull() {
            addCriterion("image_file_path is not null");
            return (Criteria) this;
        }

        public Criteria andImageFilePathEqualTo(String value) {
            addCriterion("image_file_path =", value, "imageFilePath");
            return (Criteria) this;
        }

        public Criteria andImageFilePathNotEqualTo(String value) {
            addCriterion("image_file_path <>", value, "imageFilePath");
            return (Criteria) this;
        }

        public Criteria andImageFilePathGreaterThan(String value) {
            addCriterion("image_file_path >", value, "imageFilePath");
            return (Criteria) this;
        }

        public Criteria andImageFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("image_file_path >=", value, "imageFilePath");
            return (Criteria) this;
        }

        public Criteria andImageFilePathLessThan(String value) {
            addCriterion("image_file_path <", value, "imageFilePath");
            return (Criteria) this;
        }

        public Criteria andImageFilePathLessThanOrEqualTo(String value) {
            addCriterion("image_file_path <=", value, "imageFilePath");
            return (Criteria) this;
        }

        public Criteria andImageFilePathLike(String value) {
            addCriterion("image_file_path like", value, "imageFilePath");
            return (Criteria) this;
        }

        public Criteria andImageFilePathNotLike(String value) {
            addCriterion("image_file_path not like", value, "imageFilePath");
            return (Criteria) this;
        }

        public Criteria andImageFilePathIn(List<String> values) {
            addCriterion("image_file_path in", values, "imageFilePath");
            return (Criteria) this;
        }

        public Criteria andImageFilePathNotIn(List<String> values) {
            addCriterion("image_file_path not in", values, "imageFilePath");
            return (Criteria) this;
        }

        public Criteria andImageFilePathBetween(String value1, String value2) {
            addCriterion("image_file_path between", value1, value2, "imageFilePath");
            return (Criteria) this;
        }

        public Criteria andImageFilePathNotBetween(String value1, String value2) {
            addCriterion("image_file_path not between", value1, value2, "imageFilePath");
            return (Criteria) this;
        }

        public Criteria andFavoritIsNull() {
            addCriterion("favorit is null");
            return (Criteria) this;
        }

        public Criteria andFavoritIsNotNull() {
            addCriterion("favorit is not null");
            return (Criteria) this;
        }

        public Criteria andFavoritEqualTo(Integer value) {
            addCriterion("favorit =", value, "favorit");
            return (Criteria) this;
        }

        public Criteria andFavoritNotEqualTo(Integer value) {
            addCriterion("favorit <>", value, "favorit");
            return (Criteria) this;
        }

        public Criteria andFavoritGreaterThan(Integer value) {
            addCriterion("favorit >", value, "favorit");
            return (Criteria) this;
        }

        public Criteria andFavoritGreaterThanOrEqualTo(Integer value) {
            addCriterion("favorit >=", value, "favorit");
            return (Criteria) this;
        }

        public Criteria andFavoritLessThan(Integer value) {
            addCriterion("favorit <", value, "favorit");
            return (Criteria) this;
        }

        public Criteria andFavoritLessThanOrEqualTo(Integer value) {
            addCriterion("favorit <=", value, "favorit");
            return (Criteria) this;
        }

        public Criteria andFavoritIn(List<Integer> values) {
            addCriterion("favorit in", values, "favorit");
            return (Criteria) this;
        }

        public Criteria andFavoritNotIn(List<Integer> values) {
            addCriterion("favorit not in", values, "favorit");
            return (Criteria) this;
        }

        public Criteria andFavoritBetween(Integer value1, Integer value2) {
            addCriterion("favorit between", value1, value2, "favorit");
            return (Criteria) this;
        }

        public Criteria andFavoritNotBetween(Integer value1, Integer value2) {
            addCriterion("favorit not between", value1, value2, "favorit");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table miui
     *
     * @mbggenerated do_not_delete_during_merge Sat Sep 22 18:45:34 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table miui
     *
     * @mbggenerated Sat Sep 22 18:45:34 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}