package com.example.invoke.model;

import java.util.Date;

public class Movie {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.id
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.title
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.cover_url
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    private String coverUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.rate
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    private String rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.ctime
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.region
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.duration
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    private String duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.director
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    private String director;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.actors
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    private String actors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.release_time
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    private String releaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.url
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.id
     *
     * @return the value of movie.id
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.id
     *
     * @param id the value for movie.id
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.title
     *
     * @return the value of movie.title
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.title
     *
     * @param title the value for movie.title
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.cover_url
     *
     * @return the value of movie.cover_url
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public String getCoverUrl() {
        return coverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.cover_url
     *
     * @param coverUrl the value for movie.cover_url
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.rate
     *
     * @return the value of movie.rate
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public String getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.rate
     *
     * @param rate the value for movie.rate
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public void setRate(String rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.ctime
     *
     * @return the value of movie.ctime
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.ctime
     *
     * @param ctime the value for movie.ctime
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.region
     *
     * @return the value of movie.region
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.region
     *
     * @param region the value for movie.region
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.duration
     *
     * @return the value of movie.duration
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.duration
     *
     * @param duration the value for movie.duration
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public void setDuration(String duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.director
     *
     * @return the value of movie.director
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.director
     *
     * @param director the value for movie.director
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public void setDirector(String director) {
        this.director = director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.actors
     *
     * @return the value of movie.actors
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public String getActors() {
        return actors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.actors
     *
     * @param actors the value for movie.actors
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public void setActors(String actors) {
        this.actors = actors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.release_time
     *
     * @return the value of movie.release_time
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public String getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.release_time
     *
     * @param releaseTime the value for movie.release_time
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public void setReleaseTime(String releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.url
     *
     * @return the value of movie.url
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.url
     *
     * @param url the value for movie.url
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }
}