package com.example.invoke.model;

import java.util.Date;

public class Music {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.id
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.tag
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.content
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.ctime
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.id
     *
     * @return the value of music.id
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.id
     *
     * @param id the value for music.id
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.tag
     *
     * @return the value of music.tag
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.tag
     *
     * @param tag the value for music.tag
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.content
     *
     * @return the value of music.content
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.content
     *
     * @param content the value for music.content
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.ctime
     *
     * @return the value of music.ctime
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.ctime
     *
     * @param ctime the value for music.ctime
     *
     * @mbggenerated Fri Oct 26 14:23:43 CST 2018
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}