package com.example.invoke.model;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.Collection;
import java.util.Date;

public class User implements UserDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.login_name
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.head_url
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private String headUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.delstatus
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private Integer delstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.isadmin
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private String isadmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.status
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ctime
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.utime
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private Date utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.dtime
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private Date dtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.operator
     *
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    private String operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.login_name
     *
     * @return the value of user.login_name
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.login_name
     *
     * @param loginName the value for user.login_name
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public String getPassword() {
        return password;
    }

    @Override
    public String getUsername() {
        return this.loginName;
    }

    @Override
    public boolean isAccountNonExpired() {
        return false;
    }

    @Override
    public boolean isAccountNonLocked() {
        return false;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return false;
    }

    @Override
    public boolean isEnabled() {
        return false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.head_url
     *
     * @return the value of user.head_url
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public String getHeadUrl() {
        return headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.head_url
     *
     * @param headUrl the value for user.head_url
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.delstatus
     *
     * @return the value of user.delstatus
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public Integer getDelstatus() {
        return delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.delstatus
     *
     * @param delstatus the value for user.delstatus
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setDelstatus(Integer delstatus) {
        this.delstatus = delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.isadmin
     *
     * @return the value of user.isadmin
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public String getIsadmin() {
        return isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.isadmin
     *
     * @param isadmin the value for user.isadmin
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setIsadmin(String isadmin) {
        this.isadmin = isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile
     *
     * @return the value of user.mobile
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile
     *
     * @param mobile the value for user.mobile
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.status
     *
     * @return the value of user.status
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.status
     *
     * @param status the value for user.status
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ctime
     *
     * @return the value of user.ctime
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ctime
     *
     * @param ctime the value for user.ctime
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.utime
     *
     * @return the value of user.utime
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.utime
     *
     * @param utime the value for user.utime
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.dtime
     *
     * @return the value of user.dtime
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public Date getDtime() {
        return dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.dtime
     *
     * @param dtime the value for user.dtime
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setDtime(Date dtime) {
        this.dtime = dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.operator
     *
     * @return the value of user.operator
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.operator
     *
     * @param operator the value for user.operator
     * @mbggenerated Mon Aug 13 13:12:31 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }
}